import type { PricingPackage } from "@/lib/types";

/**
 * ডিফল্ট প্রাইসিং — Codemyst_Pricing.docx + নতুন সার্ভিস (Apps, AI Automation, AI Agent)।
 * ক্যাটাগরি: free / web / apps / ai-automation / ai-agents / update / maintenance / custom
 * /admin/services → "ডিফল্ট ক্যাটাগরি ও প্রাইসিং লোড" বাটনে সিড হয়।
 */
export type PackageSeed = Omit<PricingPackage, "id">;

export const DEFAULT_PRICING: PackageSeed[] = [
  // ── ফ্রি সার্ভিস ──
  {
    category: "web-free",
    categoryName: "ফ্রি স্টার্টার",
    name: "Starter Launch (Free)",
    price: 0,
    priceType: "fixed",
    features: [
      "১ পেজের সাইট (Landing page / Digital visiting card)",
      "Contact Page",
      "Fast reload, Super Responsive",
      "Free subdomain",
      "Animation",
      "WhatsApp / Call / Email বাটন",
      "Google Map, Social link",
    ],
    delivery: "১২–১৮ ঘণ্টায় live",
    note: "Revision ১ বার · আনলিমিটেড",
    active: true,
    sortOrder: 1,
  },

  // ── ওয়েব ডেভেলপমেন্ট ──
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Portfolio — Starter",
    price: 500,
    originalPrice: 800,
    priceType: "fixed",
    features: ["১–৩ পেজ", "Responsive", "Contact form", "Domain setup"],
    active: true,
    sortOrder: 2,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Portfolio — Standard",
    price: 1500,
    priceType: "fixed",
    features: ["৫ পেজ", "নিজস্ব domain setup", "Animation", "Gallery"],
    active: true,
    sortOrder: 3,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Portfolio — Premium",
    price: 3500,
    originalPrice: 5000,
    priceType: "fixed",
    features: [
      "Next.js",
      "SEO",
      "Animation",
      "Dark mode",
      "Admin panel",
      "PWA",
      "AI integration",
      "Multi language",
    ],
    popular: true,
    active: true,
    sortOrder: 4,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Business — Starter",
    price: 500,
    priceType: "fixed",
    features: ["৩ পেজ", "Responsive", "WhatsApp/Contact button", "Domain setup"],
    active: true,
    sortOrder: 5,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Business — Standard",
    price: 4000,
    originalPrice: 5500,
    priceType: "fixed",
    features: [
      "৭ পেজ",
      "Admin panel (নিজে content বদলাতে পারবেন)",
      "Basic SEO",
      "PWA",
      "Multi language",
      "Multi theme",
    ],
    popular: true,
    active: true,
    sortOrder: 6,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Business — Premium",
    price: 15000,
    priceType: "fixed",
    features: [
      "১৫ পেজ পর্যন্ত",
      "bKash / Nagad / SSLCommerz payment",
      "Next.js + TypeScript",
    ],
    active: true,
    sortOrder: 7,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "LMS — Basic",
    price: 8000,
    priceType: "fixed",
    features: ["একজন শিক্ষক/প্রতিষ্ঠান", "Course, Video/PDF", "Student login"],
    active: true,
    sortOrder: 8,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "LMS — Standard",
    price: 20000,
    priceType: "fixed",
    features: ["Quiz", "Certificate", "Payment", "Progress tracking"],
    active: true,
    sortOrder: 9,
  },
  {
    category: "web",
    categoryName: "ওয়েব ডেভেলপমেন্ট",
    name: "Blog / News Portal",
    price: 500,
    priceType: "from",
    features: [
      "Admin panel",
      "Category/Tag, Search",
      "SEO",
      "Multi-author, Breaking news (Portal)",
      "AdSense slot (Portal)",
    ],
    note: "Blog ৳৫০০ · News Portal ৳৫,০০০ থেকে",
    active: true,
    sortOrder: 10,
  },

  // ── মোবাইল ও ডেস্কটপ অ্যাপ ──
  {
    category: "apps-general",
    categoryName: "অ্যাপ প্যাকেজ",
    name: "Android App",
    price: 15000,
    priceType: "from",
    features: [
      "Flutter / Kotlin",
      "Play Store publish",
      "Push notification ready",
      "Admin panel + API",
    ],
    delivery: "৩–৫ সপ্তাহ",
    active: true,
    sortOrder: 11,
  },
  {
    category: "apps-general",
    categoryName: "অ্যাপ প্যাকেজ",
    name: "iOS App",
    price: 25000,
    priceType: "from",
    features: [
      "Swift / Flutter",
      "App Store publish",
      "Push notification ready",
      "Apple guideline compliant",
    ],
    delivery: "৪–৬ সপ্তাহ",
    active: true,
    sortOrder: 12,
  },
  {
    category: "apps-general",
    categoryName: "অ্যাপ প্যাকেজ",
    name: "Cross-Platform (Android + iOS)",
    price: 30000,
    originalPrice: 40000,
    priceType: "from",
    features: [
      "এক কোডবেসে দুই প্ল্যাটফর্ম",
      "Flutter",
      "Play Store + App Store publish",
      "Push notification, Offline mode",
    ],
    popular: true,
    delivery: "৪–৮ সপ্তাহ",
    active: true,
    sortOrder: 13,
  },
  {
    category: "apps-general",
    categoryName: "অ্যাপ প্যাকেজ",
    name: "Desktop App",
    price: 10000,
    priceType: "from",
    features: ["Windows / macOS", "Electron / Tauri", "Offline-first", "Auto update"],
    delivery: "৩–৪ সপ্তাহ",
    active: true,
    sortOrder: 14,
  },

  // ── AI অটোমেশন ──
  {
    category: "auto-general",
    categoryName: "অটোমেশন প্যাকেজ",
    name: "AI Workflow Automation",
    price: 5000,
    priceType: "from",
    features: [
      "n8n / Make / Zapier workflow",
      "ডেটা এন্ট্রি অটোমেশন",
      "Email/Sheets/CRM ইন্টিগ্রেশন",
      "Schedule + trigger",
    ],
    popular: true,
    delivery: "৩–৭ দিন",
    active: true,
    sortOrder: 15,
  },
  {
    category: "auto-general",
    categoryName: "অটোমেশন প্যাকেজ",
    name: "Business Process Automation",
    price: 8000,
    priceType: "from",
    features: [
      "ইনভয়েস/রিপোর্ট অটো-জেনারেশন",
      "WhatsApp/Email auto-reply",
      "ডকুমেন্ট parsing (AI OCR)",
      "Custom dashboard",
    ],
    delivery: "১–২ সপ্তাহ",
    active: true,
    sortOrder: 16,
  },
  {
    category: "auto-general",
    categoryName: "অটোমেশন প্যাকেজ",
    name: "AI Chatbot Integration",
    price: 4000,
    priceType: "from",
    features: [
      "ওয়েবসাইটে AI chatbot",
      "আপনার বিজনেস ডেটায় ট্রেইনড",
      "WhatsApp/ Messenger-এও",
      "Lead capture",
    ],
    delivery: "৩–৫ দিন",
    active: true,
    sortOrder: 17,
  },

  // ── AI এজেন্ট ──
  {
    category: "agents-general",
    categoryName: "এজেন্ট প্যাকেজ",
    name: "Custom AI Agent",
    price: 8000,
    priceType: "from",
    features: [
      "কাস্টম task agent (research/data/support)",
      "Tool use + API integration",
      "Memory + scheduling",
      "Dashboard-এ মনিটরিং",
    ],
    popular: true,
    delivery: "১–২ সপ্তাহ",
    active: true,
    sortOrder: 18,
  },
  {
    category: "agents-general",
    categoryName: "এজেন্ট প্যাকেজ",
    name: "WhatsApp AI Sales Agent",
    price: 12000,
    originalPrice: 16000,
    priceType: "from",
    features: [
      "২৪/৭ অটো সেলস রিপ্লাই",
      "প্রোডাক্ট ক্যাটালগ বুঝে অফার",
      "অর্ডার কোয়ালিফাই + lead সেভ",
      "অ্যাডমিন নোটিফিকেশন",
    ],
    delivery: "১–২ সপ্তাহ",
    active: true,
    sortOrder: 19,
  },
  {
    category: "agents-general",
    categoryName: "এজেন্ট প্যাকেজ",
    name: "AI Knowledge Assistant (RAG)",
    price: 15000,
    priceType: "from",
    features: [
      "আপনার ডকুমেন্ট/ওয়েবসাইট থেকে উত্তর",
      "RAG pipeline (vector search)",
      "Team access + permission",
      "বাংলা + English",
    ],
    delivery: "২–৩ সপ্তাহ",
    active: true,
    sortOrder: 20,
  },

  // ── Update Service ──
  {
    category: "update-single",
    categoryName: "আপডেট",
    name: "Single Update",
    price: 300,
    priceType: "from",
    features: [
      "Content update (text/image/video)",
      "Design পরিবর্তন",
      "নতুন পেজ",
      "Bug fix",
      "Speed optimization",
    ],
    active: true,
    sortOrder: 21,
  },
  {
    category: "update-single",
    categoryName: "আপডেট",
    name: "Update Pack",
    price: 1000,
    priceType: "fixed",
    features: ["৫টা ছোট কাজ এক প্যাকে"],
    active: true,
    sortOrder: 22,
  },

  // ── Maintenance & Support ──
  {
    category: "maint-general",
    categoryName: "মেইনটেন্যান্স",
    name: "Basic",
    price: 200,
    priceType: "monthly",
    features: ["Uptime check", "মাসে ১টা ছোট update"],
    active: true,
    sortOrder: 23,
  },
  {
    category: "maint-general",
    categoryName: "মেইনটেন্যান্স",
    name: "Standard",
    price: 800,
    priceType: "monthly",
    features: ["মাসে ৪টা update", "Backup", "Priority support"],
    popular: true,
    active: true,
    sortOrder: 24,
  },

  // ── কাস্টম প্রজেক্ট ──
  {
    category: "web-custom",
    categoryName: "কাস্টম প্রজেক্ট",
    name: "Partner Plan",
    price: null,
    priceType: "quote",
    features: [
      "যাদের সাইট থেকে সরাসরি আয় হয় (Shop, LMS, Blog/News, Booking)",
      "ফ্রি বিল্ড — আয়ের ২০% শেয়ার",
      "সব order/payment admin panel-এ",
      "আপনার dashboard access",
    ],
    note: "শর্তসাপেক্ষে",
    active: true,
    sortOrder: 25,
  },
  {
    category: "web-custom",
    categoryName: "কাস্টম প্রজেক্ট",
    name: "Custom Web / App Application",
    price: 1000,
    priceType: "from",
    features: [
      "আইডিয়া আলোচনা + সহজ wireframe (ফ্রি)",
      "Scope দেখে quote",
      "Web, Mobile বা Desktop — যেকোনো প্ল্যাটফর্ম",
    ],
    delivery: "Scope অনুযায়ী",
    active: true,
    sortOrder: 26,
  },
];
